kind: "pipeline"
name: "default"
type: "docker"
trigger:
  branch:
    - master

steps:
  - name: Restore Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: "Build"
    image: "node:lts-buster-slim"
    pull: if-not-exists
    commands:
      - apt-get update
      - apt-get install openssl -y -qq
      - yarn install --frozen-lockfile
      - yarn tsc
  - name: Rebuild Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
  - name: Publish Release
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: github_token
    when:
      event: 
        - tag
      branch:
        - master
  - name: Publish Bot
    pull: if-not-exists
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - tag
    settings:
      tags: latest
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/dynamicabot/dynamica
      auto_tag: true
      registry: ghcr.io
      cache_from: ghcr.io/dynamicabot/dynamica
volumes:
  - name: cache
    host:
      path: /tmp/cache
