---
kind: "pipeline"
name: "Build"
type: "docker"

steps:
  - name: Restore Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: "Build & Check Types"
    image: "node:16-alpine"
    pull: if-not-exists
    environment:
      TYPE_CHECKING: "true"
    commands:
      - apk update --no-cache
      - apk add --no-cache python3 make gcc g++ curl
      - yarn install --frozen-lockfile
      - yarn generate
      - yarn build
  - name: Rebuild Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache
trigger:
  branches:
    - master
  events:
    - pull_request
    - tag
---
kind: "pipeline"
name: "Publish GHCR.io Tagged Release"
depends_on:
  - "Build"
type: "docker"
trigger:
  event:
    - tag
  branch:
    - master
steps:
  - name: Publish Bot on ghcr.io
    pull: if-not-exists
    image: plugins/docker
    settings:
      target: runner
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/dynamicabot/dynamica
      auto_tag: true
      registry: ghcr.io
      build_args_from_env:
        - DRONE_TAG
volumes:
  - name: cache
    host:
      path: /tmp/cache
---
kind: "pipeline"
name: "Publish GHCR.io Tagged Pterodactyl Release"
depends_on:
  - "Build"
type: "docker"
trigger:
  event:
    - tag
  branch:
    - master
steps:
  - name: Publish Pterodactyl Bot on ghcr.io
    pull: if-not-exists
    image: plugins/docker
    settings:
      target: pterodactyl
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/dynamicabot/dynamica
      auto_tag: true
      registry: ghcr.io
      auto_tag_suffix: pterodactyl
      build_args_from_env:
        - DRONE_TAG
volumes:
  - name: cache
    host:
      path: /tmp/cache
