---
kind: "pipeline"
name: "Build"
type: "docker"

steps:
  - name: Restore Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: "Build"
    image: "node:lts-buster-slim"
    pull: if-not-exists
    commands:
      - apt-get update
      - apt-get install openssl -y -qq
      - yarn install --frozen-lockfile
      - yarn build
  - name: Rebuild Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache
---
kind: "pipeline"
name: "Publish GHCR.io Release"
depends_on:
  - "Build"
type: "docker"
trigger:
  event:
    - tag
  branch:
    - master
steps:
  - name: Publish Bot on ghcr.io
    pull: if-not-exists
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - tag
    settings:
      target: runner
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/dynamicabot/dynamica
      auto_tag: true
      registry: ghcr.io
      build_args_from_env:
        - DRONE_TAG
volumes:
  - name: cache
    host:
      path: /tmp/cache
---
kind: "pipeline"
name: "Publish GHCR.io Pterodactyl Release"
depends_on:
  - "Build"
type: "docker"
trigger:
  event:
    - tag
  branch:
    - master
steps:
  - name: Publish Pterodactyl Bot on ghcr.io
    pull: if-not-exists
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - tag
    settings:
      tags:
        - pterodactyl
      target: pterodactyl
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/dynamicabot/dynamica
      auto_tag: true
      registry: ghcr.io
      auto_tag_suffix: pterodactyl
      build_args_from_env:
        - DRONE_TAG
volumes:
  - name: cache
    host:
      path: /tmp/cache
---
kind: signature
hmac: 35fc080ab5d33306e5e274ea237ea02dea616dc89207f37b40aad784a824398f
