kind: "pipeline"
name: "default"
type: "docker"
steps:
  - name: Restore Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: "build"
    image: "node:lts-buster-slim"
    pull: if-not-exists
    commands:
      - apt-get update
      - apt-get install openssl -y -qq
      - yarn install --frozen-lockfile
      - yarn tsc
  - name: Rebuild Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

  - name: Publish Bot
    pull: if-not-exists
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - promote
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/sebasptsch/dynamica
      registry: ghcr.io
volumes:
  - name: cache
    host:
      path: /tmp/cache
