env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
settings:
  import/resolver: { 'typescript': {} }
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules: { 'prettier/prettier': 'error' }
