name: Feature request
description: Suggest an idea for this project
labels:
  - "enhancement"

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Feature request description"
      description: "Describe the feature request"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: "What type of feature is this?"
      options:
        - "Command"
        - "Core"
        - "Dependancy"
        - "CI/Self-hosting method"
