---
- hosts: all
  tasks:
    - name: Deploy Dynamica
      community.docker.docker_container:
        name: Dynamica
        image: ghcr.io/dynamicabot/dynamica:2022.4.3
        volumes:
          - ~/Dynamica/config:/app/config
        env:
          TOKEN: "{{ lookup('env', 'TOKEN') }}"
          CLIENT_ID: "{{ lookup('env', 'CLIENT_ID') }}"
        ports:
          - 5555:5555
          - 4000:4000
        restart_policy: unless-stopped
