import Helps from './classes/Helps';
import AliasesHelp from './help/AliasesHelp';
import AliasHelp from './help/AliasHelp';
import AllowjoinHelp from './help/AllowjoinHelp';
import AllyourbaseHelp from './help/AllyourbaseHelp';
import BitrateHelp from './help/BitrateHelp';
import CreateHelp from './help/CreateHelp';
import GeneralHelp from './help/GeneralHelp';
import HelpHelp from './help/HelpHelp';
import InfoHelp from './help/InfoHelp';
import JoinHelp from './help/JoinHelp';
import LimitHelp from './help/LimitHelp';
import LockHelp from './help/LockHelp';
import NameHelp from './help/NameHelp';
import PermissionHelp from './help/PermissionHelp';
import PingHelp from './help/PingHelp';
import TemplateHelp from './help/TemplateHelp';
import TransferHelp from './help/TransferHelp';
import UnlockHelp from './help/UnlockHelp';
import VersionHelp from './help/VersionHelp';

const registerHelp = () => {
  Helps.register(new AliasHelp());
  Helps.register(new AllowjoinHelp());
  Helps.register(new AllyourbaseHelp());
  Helps.register(new BitrateHelp());
  Helps.register(new CreateHelp());
  Helps.register(new GeneralHelp());
  Helps.register(new HelpHelp());
  Helps.register(new InfoHelp());
  Helps.register(new JoinHelp());
  Helps.register(new LimitHelp());
  Helps.register(new LockHelp());
  Helps.register(new NameHelp());
  Helps.register(new PermissionHelp());
  Helps.register(new PingHelp());
  Helps.register(new TemplateHelp());
  Helps.register(new TransferHelp());
  Helps.register(new UnlockHelp());
  Helps.register(new VersionHelp());
  Helps.register(new AliasesHelp());
};

export default registerHelp;
