import Commands from './classes/Commands';
import AliasCommand from './commands/AliasCommand';
import AliasesCommand from './commands/AliasesCommand';
import AllowjoinCommand from './commands/AllowjoinCommand';
import AllyourbaseCommand from './commands/AllyourbaseCommand';
import BitrateCommand from './commands/BitrateCommand';
import CreateCommand from './commands/CreateCommand';
import GeneralCommand from './commands/GeneralCommand';
import HelpCommand from './commands/HelpCommand';
import InfoCommand from './commands/InfoCommand';
import JoinCommand from './commands/JoinCommand';
import LimitCommand from './commands/LimitCommand';
import LockCommand from './commands/LockCommand';
import NameCommand from './commands/NameCommand';
import PermissionCommand from './commands/PermissionCommand';
import PingCommand from './commands/PingCommand';
import TemplateCommand from './commands/TemplateCommand';
import TransferCommand from './commands/TransferCommand';
import UnlockCommand from './commands/UnlockCommand';
import VersionCommand from './commands/VersionCommand';

const registerCommands = () => {
  Commands.register(new AliasCommand());
  Commands.register(new AllowjoinCommand());
  Commands.register(new AllyourbaseCommand());
  Commands.register(new BitrateCommand());
  Commands.register(new CreateCommand());
  Commands.register(new GeneralCommand());
  Commands.register(new HelpCommand());
  Commands.register(new InfoCommand());
  Commands.register(new JoinCommand());
  Commands.register(new LimitCommand());
  Commands.register(new LockCommand());
  Commands.register(new NameCommand());
  Commands.register(new PermissionCommand());
  Commands.register(new PingCommand());
  Commands.register(new TemplateCommand());
  Commands.register(new TransferCommand());
  Commands.register(new UnlockCommand());
  Commands.register(new VersionCommand());
  Commands.register(new AliasesCommand());
};

export default registerCommands;
