name: Docker Build

on:
  workflow_dispatch:
    inputs:
      pushtoregistry:
        description: 'Push the image on this run.'
        default: false
        required: false
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          push: ${{ github.event.inputs.pushtoregistry }}
          tags: ghcr.io/dynamicabot/dynamica:latest
